2021-05-01 10:20:28.315124: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-01 10:20:28.315175: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-01 10:20:40.329 | INFO     | __main__:load_description_data:106 - Pulling tagline data...
2021-05-01 10:22:30.932 | INFO     | __main__:load_description_data:119 - Tagline data pulled. 1948422 total entries
2021-05-01 10:22:31.874 | INFO     | __main__:load_book_counts_data:124 - Pulling book reading data...
2021-05-01 10:23:28.931 | INFO     | __main__:load_book_counts_data:127 - Book interactions pulled, 2360650 total interactions
2021-05-01 10:23:28.954 | INFO     | __main__:preprocess:49 - Start preprocessing
Traceback (most recent call last):
  File "model.py", line 138, in <module>
    pipeline.run()
  File "model.py", line 96, in run
    train_processed, test_processed, train_y, test_y = self.preprocess()
  File "model.py", line 64, in preprocess
    assert len(train_y) == len(train_x)
AssertionError
